apiVersion: v1
kind: Namespace
metadata:
  name: ns-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: ns-app
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: ""
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: ns-app
spec:
  selector:
    app: web-app
  ports:
    - name: http-web
      port: 80
      targetPort: 8080
  type: LoadBalancer
