apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
  labels:
    app: my-web-app
spec:
  replicas: 3  # Запускаем 3 реплики приложения для обеспечения высокой доступности и нагрузки
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: my-web-app
        image: my-web-app:latest  # Имя образа приложения
        ports:
        - containerPort: 80  # Порт, который приложение использует
        readinessProbe:  # Проверка готовности контейнера
          httpGet:
            path: /health  # Путь для проверки готовности
            port: 80
          initialDelaySeconds: 10  # Задержка перед первой проверкой готовности
          periodSeconds: 5  # Период проверки готовности
        livenessProbe:  # Проверка живости контейнера
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30  # Задержка перед первой проверкой живости
          periodSeconds: 10  # Период проверки живости
      affinity:  # Настройка для распределения подов по зонам
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: my-web-app
            topologyKey: "topology.kubernetes.io/zone"  # Распределение по зонам для обеспечения доступности

---
apiVersion: v1
kind: Service
metadata:
  name: my-web-app-service
spec:
  selector:
    app: my-web-app
  ports:
  - protocol: TCP
    port: 80  # Порт сервиса
    targetPort: 80  # Порт контейнера
  type: LoadBalancer  # Тип сервиса для внешнего доступа к приложению

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-web-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-web-app
  minReplicas: 3  # Минимальное количество реплик
  maxReplicas: 10  # Максимальное количество реплик для масштабирования
  targetCPUUtilizationPercentage: 70  # Целевое использование CPU для автоматического масштабирования
